# catalog.py
# Catalogue produits (Banque Populaire) - démonstrateur

PRODUCT_CATALOG = [
    {
        "id": "LIVRET_A",
        "name": "Livret A",
        "type": "epargne_securisee",
        "horizon_min_years": 0,
        "horizon_max_years": 3,
        "liquidity": "forte",
        "risk_profiles_allowed": ["Sécurisé", "Équilibré", "Dynamique"],
        "goals": ["precaution", "court_terme", "besoin_liquidite"],
        "contraindications": ["recherche_performance_long_terme"],
        "priority": 1.0,
        "projection": {"type": "fixed_rate", "fixed_rate": 0.03, "supports_VI_VP": True},
    },
    {
        "id": "AV",
        "name": "Assurance Vie",
        "type": "investissement",
        "horizon_min_years": 4,
        "horizon_max_years": None,
        "liquidity": "moyenne",
        "risk_profiles_allowed": ["Sécurisé", "Équilibré", "Dynamique"],
        "goals": ["projet", "investissement", "flexibilite", "transmission"],
        "contraindications": ["besoin_liquidite_immediate", "horizon_tres_court"],
        "priority": 1.1,
        "projection": {"type": "risk_based", "fixed_rate": None, "supports_VI_VP": True},
    },
    {
        "id": "PEA",
        "name": "PEA",
        "type": "investissement_actions",
        "horizon_min_years": 5,
        "horizon_max_years": None,
        "liquidity": "moyenne",
        "risk_profiles_allowed": ["Équilibré", "Dynamique"],
        "goals": ["investissement", "long_terme", "actions"],
        "contraindications": ["profil_securise", "besoin_liquidite_immediate"],
        "priority": 1.0,
        "projection": {"type": "risk_based", "fixed_rate": None, "supports_VI_VP": True},
    },
    {
        "id": "CTO",
        "name": "Compte-titres (CTO)",
        "type": "investissement_libre",
        "horizon_min_years": 3,
        "horizon_max_years": None,
        "liquidity": "moyenne",
        "risk_profiles_allowed": ["Équilibré", "Dynamique"],
        "goals": ["investissement", "diversification", "actions", "obligations"],
        "contraindications": ["profil_securise", "besoin_liquidite_immediate"],
        "priority": 0.95,
        "projection": {"type": "risk_based", "fixed_rate": None, "supports_VI_VP": True},
    },
    {
        "id": "PER",
        "name": "PER individuel",
        "type": "retraite",
        "horizon_min_years": 8,
        "horizon_max_years": None,
        "liquidity": "faible",
        "risk_profiles_allowed": ["Équilibré", "Dynamique"],
        "goals": ["retraite", "optimisation_fiscale"],
        "contraindications": ["projet_court_terme", "besoin_liquidite_immediate"],
        "priority": 1.05,
        "projection": {"type": "risk_based", "fixed_rate": None, "supports_VI_VP": True},
    },
]